name: cloudcrawler auto deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "README.md"
        REMOTE_HOST: "118.178.181.97"
        REMOTE_USER: "root"
        TARGET: "/home/README.md"
